# Is xx-month-old baby heavier than 20 pounds?

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lhi: <http://www.semanticweb.org/theorist/ontologies/2020/10/root-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

ASK {
	?class rdfs:subClassOf* lhi:15MonthOld .
  	{?class (rdfs:subClassOf)
     [
            a owl:Restriction ;
            owl:onProperty lhi:hasBoyWeight ;
           (owl:someValuesFrom|owl:hasValue) ?value;
                                           ] .}
  	UNION  {?class (rdfs:subClassOf)
     [
            a owl:Restriction ;
            owl:onProperty lhi:hasGirlWeight ;
           (owl:someValuesFrom|owl:hasValue) ?value;
] .}
  FILTER (?value > 20)
}