# What should I do for potty training of xx-month-old?

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lhi: <http://www.semanticweb.org/theorist/ontologies/2020/10/root-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?training 
WHERE { 
  ?stage rdfs:subClassOf* lhi:16MonthOld .
  ?stage (rdfs:subClassOf)
     [
            a owl:Restriction ;
            owl:onProperty lhi:do ;
            (owl:someValuesFrom) ?trainings;
     ] .
  ?trainings rdfs:subClassOf* lhi:PottyTraining .  
  ?training rdf:type ?trainings.
}