# What should my xx-month-old be speaking?

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lhi: <http://www.semanticweb.org/theorist/ontologies/2020/10/root-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?speech 
WHERE { 
  	?class rdfs:subClassOf* lhi:16MonthOld .
	?class (rdfs:subClassOf)
   [
          a owl:Restriction ;
          owl:onProperty lhi:do ;
         (owl:someValuesFrom) ?speechlevel;
   ] .
  ?speechlevel rdfs:subClassOf lhi:Speech .
  ?speech rdf:type ?speechlevel
}